version: '3.7'
services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    networks:
      - facialapp

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    command: ["yarn", "start"]
    networks:
      - facialapp

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - facialapp

networks:
  facialapp:
    driver: bridge

